export const SITE = {
  site: {
    url: "https://vndo.vn",
  },
  author: {
    firstName: "Do Quoc",
    lastName: "Viet",
    fullName: "Do Quoc Viet",
    fullNameVi: "Đỗ Quốc Việt",
    shortName: "vietdoo",
    alternateNames: [
      "Đỗ Quốc Việt",
      "Do Quoc Viet",
      "vietdoo",
      "Đỗ Quốc Việt VNPT",
      "Do Quoc Viet VNPT",
      "vietdoo-folio",
    ],
    jobTitle: "Software Engineer @ VNPT Group",
    company: "VNPT Group",
    companyVi: "Tập đoàn Bưu chính Viễn thông Việt Nam",
    project: "National Public Service Portal (Cổng Dịch vụ công Quốc gia)",
    twitterHandle: "vietdoo", // without "@"
    keywords: [
      "Đỗ Quốc Việt",
      "Do Quoc Viet",
      "vietdoo",
      "Đỗ Quốc Việt VNPT",
      "Do Quoc Viet VNPT",
      "vietdoo-folio",
      "Software Engineer",
      "VNPT Group",
      "Tập đoàn Bưu chính Viễn thông Việt Nam",
      "Cổng Dịch vụ công Quốc gia",
      "National Public Service Portal",
      "Software Engineer VNPT",
      "Big Data Engineer Vietnam",
      "Apache Spark",
      "Apache Kafka",
      "Hadoop HDFS",
      "Distributed Systems",
      "Data Pipelines",
      "Python",
      "C++",
      "Spring Boot",
      "FastAPI",
      "Cloud-Native Microservices",
      "Redis",
      "PostgreSQL",
      "SQL",
      "NoSQL",
      "SQL / NoSQL",
      "Kubernetes",
      "Docker",
      "Linux",
      "TypeScript",
      "Next.js",
      "AI Agent Architecture",
      "Handover Architecture",
    ],
  },
  location: {
    countryName: "Vietnam",
    countryCode: "VN",
    timezone: "Asia/Ho_Chi_Minh",
  },
  links: {
    github: "https://github.com/vietdoo",
    linkedin: "https://www.linkedin.com/in/vietdoo/",
    medium: "https://vndo.vn",
    dribbble: "https://vndo.vn",
    email: "vietdoo@outlook.com",
    goodreads: "https://www.goodreads.com/user/show/165632513",
  },
  cal: {
    username: "vietdoo",
    durationNamespace: "15min",
    origin: "https://cal.com",
  },
  visitedCountries: ["Vietnam"],
  visitedProvinces: [
    "Ha Noi",
    "Ho Chi Minh",
    "Da Nang",
    "Quang Ninh",
    "Lam Dong",
    "Dong Nai",
    "Tay Ninh",
    "Khanh Hoa",
    "Thanh Hoa",
    "Ninh Binh",
  ],
};
